title: <p align="center"> Vishnu Venu </p>
logo: /assets/img/profile.jpeg

description:
  <p align="center">
  <a href="Resume/Vishnu Venu CV.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vishnu-venu-543152b1/">LinkedIn</a> |
  <a href="https://github.com/vishnuvenu432">GitHub</a>
  
  <br>
  I am fascinated utilizing my GIS and Remote Sensing knowledge in a reputed organization. I believe my competence in 
  Satellite Imagery and Data Handling skills will equip me for a challenging role within this industrious field. To work at 
  a firm where I may develop experience and knowledge in the subject of mining, and then apply my analytical, technical, 
  and management abilities to help the company achieve its objectives.
  <br>
  </p>
  

theme: jekyll-theme-minimal
